language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
services:
  - redis-server
before_script:
  - cp .env.travis .env
  - psql -c 'create database travis_ci_test;' -U postgres
  - composer install
  - php artisan migrate
matrix:
 allow_failures:
   - php: 7.0
   - php: nightly
