language: php
php:
  - 5.6
  - 7.0
  - nightly
services:
  - redis-server
before_script:
  - cp .env.testing .env
  - rm phpunit.xml
  - cp phpunit.travis.xml phpunit.xml
  - psql -c 'create database vamsys;' -U postgres
  - composer install
  - php artisan migrate
matrix:
 allow_failures:
   - php: 7.0
   - php: nightly
